version: "3"
services:
  vite-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vite-app
    ports:
      - "3000:5173"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vite-app-test
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
